# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 444)
        self.port = QtWidgets.QComboBox(Form)
        self.port.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.port.setObjectName("port")
        self.speed = QtWidgets.QComboBox(Form)
        self.speed.setGeometry(QtCore.QRect(130, 100, 141, 32))
        self.speed.setObjectName("speed")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 10, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setGeometry(QtCore.QRect(270, 80, 121, 71))
        self.connectButton.setObjectName("connectButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stopMinValue = QtWidgets.QSpinBox(Form)
        self.stopMinValue.setGeometry(QtCore.QRect(120, 180, 171, 51))
        self.stopMinValue.setAlignment(QtCore.Qt.AlignCenter)
        self.stopMinValue.setMinimum(1)
        self.stopMinValue.setMaximum(1023)
        self.stopMinValue.setProperty("value", 300)
        self.stopMinValue.setObjectName("stopMinValue")
        self.runningBrightness = QtWidgets.QSpinBox(Form)
        self.runningBrightness.setGeometry(QtCore.QRect(110, 270, 171, 51))
        self.runningBrightness.setAlignment(QtCore.Qt.AlignCenter)
        self.runningBrightness.setMinimum(0)
        self.runningBrightness.setMaximum(255)
        self.runningBrightness.setProperty("value", 70)
        self.runningBrightness.setObjectName("runningBrightness")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.orangeBlinking = QtWidgets.QSpinBox(Form)
        self.orangeBlinking.setGeometry(QtCore.QRect(120, 370, 171, 51))
        self.orangeBlinking.setAlignment(QtCore.Qt.AlignCenter)
        self.orangeBlinking.setMinimum(0)
        self.orangeBlinking.setMaximum(255)
        self.orangeBlinking.setProperty("value", 50)
        self.orangeBlinking.setObjectName("orangeBlinking")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 320, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 340, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Управление переменными значениями"))
        self.label.setText(_translate("Form", "Порт"))
        self.label_2.setText(_translate("Form", "Скорость"))
        self.connectButton.setText(_translate("Form", "Подключиться"))
        self.label_3.setText(_translate("Form", "Мин. сила нажатия тормоза (1 - 1023)"))
        self.label_4.setText(_translate("Form", "Яркость ходовых огней (0-255)"))
        self.label_5.setText(_translate("Form", "Частота мигания оранжевых ламп"))
        self.label_6.setText(_translate("Form", "(0 (раз в 5мс) - 255 (раз в 3 секунды))"))
